data:
  datapath: 'data/Datasets/MG_test_short.mat'
  n_sample: 10
  length: 200   # sequence length L

model:
  layers: [ 32, 32, 32, 32, 32 ]
  modes1: [ 100, 100, 100, 100 ]
  fc_dim: 64
  act: relu

test:
  batchsize: 10
  ckpt: 'checkpoints/NAR/model.pt'


